### PR TITLE
Adds the primary model classes;

### PR DESCRIPTION
**Pull request by Yohe-Am**
Anything I'm missing? Whadya need?

### CODE REVIEW

**Comment by Karamazovian** [comment]
I was thinking we'd make the messages something akin to what element does. Meaning a single message model with a type and content and the receiver would read the contents based on what type the message was. So a regular message and any other special messages would be exactly the same.

**Comment by Karamazovian** [comment]
Also feel like we should add the `pubspec.lock` to the `gitignore`.

**Comment by Yohe-Am** [comment]
> I was thinking we'd make the messages something akin to what element does. Meaning a single message model with a type and content and the receiver would read the contents based on what type the message was. So a regular message and any other special messages would be exactly the same.

I haven't seen the matrix specs but this is similar to what you're describing. Class hierarchy aside, the JSONs are pretty similar. I have an enum in there as well though some type distinction relies upon existence of fields. 

> Also feel like we should add the `pubspec.lock` to the `gitignore`.

Checking in the `lock` files is recommended if you're making executables, I believe. Why does it bother you anyways>

**Comment by Karamazovian** [comment]
> Checking in the lock files is recommended if you're making executables, I believe. Why does it bother you anyways

It's recommended to ensure consistency, I think. and for a project of this size, we can manage. And I just don't like seeing it in the commits.

> I haven't seen the matrix specs but this is similar to what you're describing.

I haven't seen the spec either, I'm just referring to what you see when you look at the message source.

And if the `RoomEntry` is going to be the wrapper and the `TextMessage` the content, I feel like a few of the fields should be moved up the hierarchy.

**Comment by Yohe-Am** [comment]
> I feel like a few of the fields should be moved up the hierarchy.

Which fields?

**Comment by Karamazovian** [comment]
Looking at it now, nothing I suppose. I had thought that `RoomEntry` would contain the `Message` but I see that you've actually extended it.

**Pull request merged**
